// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package storedb

import (
	"context"
	"database/sql"
)

const activeDeviceSession = `-- name: ActiveDeviceSession :one
select exists(
  select 1 from devices
  inner join users on devices.user_id=users.id
  where devices.id=?1
    and devices.user_id=?2
    and users.deleted_at is null
)
`

type ActiveDeviceSessionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ActiveDeviceSession(ctx context.Context, arg ActiveDeviceSessionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, activeDeviceSession, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const activeSleepsMissingFromDevice = `-- name: ActiveSleepsMissingFromDevice :many
select sleep_sessions.id, sleep_sessions.family_id, sleep_sessions.child_id,
  sleep_sessions.started_at, children.nickname, devices.push_to_start_token,
  devices.apns_environment
from devices
inner join family_members on devices.user_id=family_members.user_id and family_members.removed_at is null
inner join sleep_sessions on family_members.family_id=sleep_sessions.family_id
inner join children on sleep_sessions.child_id=children.id
where devices.id=?1
  and devices.live_activities_enabled=1
  and devices.push_to_start_token is not null
  and sleep_sessions.ended_at is null
  and sleep_sessions.deleted_at is null
  and sleep_sessions.superseded_by_id is null
  and not exists (
    select 1 from live_activity_starts
    where live_activity_starts.session_id=sleep_sessions.id
      and live_activity_starts.device_id=devices.id
  )
`

type ActiveSleepsMissingFromDeviceRow struct {
	ID               string         `json:"id"`
	FamilyID         string         `json:"family_id"`
	ChildID          string         `json:"child_id"`
	StartedAt        string         `json:"started_at"`
	Nickname         string         `json:"nickname"`
	PushToStartToken sql.NullString `json:"push_to_start_token"`
	ApnsEnvironment  string         `json:"apns_environment"`
}

func (q *Queries) ActiveSleepsMissingFromDevice(ctx context.Context, deviceID string) ([]ActiveSleepsMissingFromDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, activeSleepsMissingFromDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveSleepsMissingFromDeviceRow{}
	for rows.Next() {
		var i ActiveSleepsMissingFromDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.ChildID,
			&i.StartedAt,
			&i.Nickname,
			&i.PushToStartToken,
			&i.ApnsEnvironment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anonymizeUser = `-- name: AnonymizeUser :execrows
update users set
  apple_subject=?1,
  display_name='',
  apple_refresh_token_ciphertext=null,
  deleted_at=?2
where id=?3 and deleted_at is null
`

type AnonymizeUserParams struct {
	AppleSubject string         `json:"apple_subject"`
	DeletedAt    sql.NullString `json:"deleted_at"`
	ID           string         `json:"id"`
}

func (q *Queries) AnonymizeUser(ctx context.Context, arg AnonymizeUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, anonymizeUser, arg.AppleSubject, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const appleRefreshTokens = `-- name: AppleRefreshTokens :many
select id, apple_refresh_token_ciphertext from users
where deleted_at is null and apple_refresh_token_ciphertext is not null
order by id
`

type AppleRefreshTokensRow struct {
	ID                          string `json:"id"`
	AppleRefreshTokenCiphertext []byte `json:"apple_refresh_token_ciphertext"`
}

func (q *Queries) AppleRefreshTokens(ctx context.Context) ([]AppleRefreshTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, appleRefreshTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppleRefreshTokensRow{}
	for rows.Next() {
		var i AppleRefreshTokensRow
		if err := rows.Scan(&i.ID, &i.AppleRefreshTokenCiphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const canRegisterLiveActivity = `-- name: CanRegisterLiveActivity :one
select exists(
  select 1 from sleep_sessions
  inner join family_members on sleep_sessions.family_id=family_members.family_id
  where sleep_sessions.id=?1
    and family_members.user_id=?2
    and family_members.removed_at is null
)
`

type CanRegisterLiveActivityParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) CanRegisterLiveActivity(ctx context.Context, arg CanRegisterLiveActivityParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, canRegisterLiveActivity, arg.SessionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const childNotificationContext = `-- name: ChildNotificationContext :one
select children.nickname, sleep_sessions.started_at
from sleep_sessions inner join children on sleep_sessions.child_id=children.id
where sleep_sessions.id=?1 and sleep_sessions.family_id=?2
`

type ChildNotificationContextParams struct {
	SessionID string `json:"session_id"`
	FamilyID  string `json:"family_id"`
}

type ChildNotificationContextRow struct {
	Nickname  string `json:"nickname"`
	StartedAt string `json:"started_at"`
}

func (q *Queries) ChildNotificationContext(ctx context.Context, arg ChildNotificationContextParams) (ChildNotificationContextRow, error) {
	row := q.db.QueryRowContext(ctx, childNotificationContext, arg.SessionID, arg.FamilyID)
	var i ChildNotificationContextRow
	err := row.Scan(&i.Nickname, &i.StartedAt)
	return i, err
}

const claimLiveActivityStart = `-- name: ClaimLiveActivityStart :execrows
insert into live_activity_starts(session_id, device_id, push_to_start_token, created_at)
values (?1, ?2, ?3, ?4)
on conflict(session_id, device_id) do nothing
`

type ClaimLiveActivityStartParams struct {
	SessionID        string `json:"session_id"`
	DeviceID         string `json:"device_id"`
	PushToStartToken string `json:"push_to_start_token"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) ClaimLiveActivityStart(ctx context.Context, arg ClaimLiveActivityStartParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimLiveActivityStart,
		arg.SessionID,
		arg.DeviceID,
		arg.PushToStartToken,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createUser = `-- name: CreateUser :exec
insert into users(id, apple_subject, display_name, apple_refresh_token_ciphertext, created_at)
values (?1, ?2, ?3, ?4, ?5)
`

type CreateUserParams struct {
	ID                          string `json:"id"`
	AppleSubject                string `json:"apple_subject"`
	DisplayName                 string `json:"display_name"`
	AppleRefreshTokenCiphertext []byte `json:"apple_refresh_token_ciphertext"`
	CreatedAt                   string `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.AppleSubject,
		arg.DisplayName,
		arg.AppleRefreshTokenCiphertext,
		arg.CreatedAt,
	)
	return err
}

const deleteDeviceForUser = `-- name: DeleteDeviceForUser :execrows
delete from devices where id=?1 and user_id=?2
`

type DeleteDeviceForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDeviceForUser(ctx context.Context, arg DeleteDeviceForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeviceForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLiveActivityToken = `-- name: DeleteLiveActivityToken :exec
delete from live_activity_tokens where token=?1
`

func (q *Queries) DeleteLiveActivityToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteLiveActivityToken, token)
	return err
}

const deleteLiveActivityTokens = `-- name: DeleteLiveActivityTokens :exec
delete from live_activity_tokens where session_id=?1
`

func (q *Queries) DeleteLiveActivityTokens(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteLiveActivityTokens, sessionID)
	return err
}

const deletePushToStartToken = `-- name: DeletePushToStartToken :exec
update devices set push_to_start_token=null where id=?1 and push_to_start_token=?2
`

type DeletePushToStartTokenParams struct {
	ID               string         `json:"id"`
	PushToStartToken sql.NullString `json:"push_to_start_token"`
}

func (q *Queries) DeletePushToStartToken(ctx context.Context, arg DeletePushToStartTokenParams) error {
	_, err := q.db.ExecContext(ctx, deletePushToStartToken, arg.ID, arg.PushToStartToken)
	return err
}

const deletePushToken = `-- name: DeletePushToken :exec
update devices set apns_token=null where id=?1 and apns_token=?2
`

type DeletePushTokenParams struct {
	ID        string         `json:"id"`
	ApnsToken sql.NullString `json:"apns_token"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.ExecContext(ctx, deletePushToken, arg.ID, arg.ApnsToken)
	return err
}

const deleteUserDevices = `-- name: DeleteUserDevices :exec
delete from devices where user_id=?1
`

func (q *Queries) DeleteUserDevices(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserDevices, userID)
	return err
}

const devicePushSettings = `-- name: DevicePushSettings :one
select apns_token, push_to_start_token, apns_environment,
  notifications_enabled, live_activities_enabled, reminder_lead_minutes
from devices where id=?1 and user_id=?2
`

type DevicePushSettingsParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type DevicePushSettingsRow struct {
	ApnsToken             sql.NullString `json:"apns_token"`
	PushToStartToken      sql.NullString `json:"push_to_start_token"`
	ApnsEnvironment       string         `json:"apns_environment"`
	NotificationsEnabled  int64          `json:"notifications_enabled"`
	LiveActivitiesEnabled int64          `json:"live_activities_enabled"`
	ReminderLeadMinutes   int64          `json:"reminder_lead_minutes"`
}

func (q *Queries) DevicePushSettings(ctx context.Context, arg DevicePushSettingsParams) (DevicePushSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, devicePushSettings, arg.ID, arg.UserID)
	var i DevicePushSettingsRow
	err := row.Scan(
		&i.ApnsToken,
		&i.PushToStartToken,
		&i.ApnsEnvironment,
		&i.NotificationsEnabled,
		&i.LiveActivitiesEnabled,
		&i.ReminderLeadMinutes,
	)
	return i, err
}

const deviceSession = `-- name: DeviceSession :one
select user_id, refresh_token_hash, refresh_expires_at
from devices
where id = ?1
`

type DeviceSessionRow struct {
	UserID           string         `json:"user_id"`
	RefreshTokenHash []byte         `json:"refresh_token_hash"`
	RefreshExpiresAt sql.NullString `json:"refresh_expires_at"`
}

func (q *Queries) DeviceSession(ctx context.Context, id string) (DeviceSessionRow, error) {
	row := q.db.QueryRowContext(ctx, deviceSession, id)
	var i DeviceSessionRow
	err := row.Scan(&i.UserID, &i.RefreshTokenHash, &i.RefreshExpiresAt)
	return i, err
}

const familyNotificationDevices = `-- name: FamilyNotificationDevices :many
select distinct devices.id, devices.apns_token, devices.push_to_start_token,
  devices.apns_environment, devices.notifications_enabled, devices.live_activities_enabled
from devices
inner join family_members on devices.user_id=family_members.user_id
where family_members.family_id=?1
  and family_members.removed_at is null
`

type FamilyNotificationDevicesRow struct {
	ID                    string         `json:"id"`
	ApnsToken             sql.NullString `json:"apns_token"`
	PushToStartToken      sql.NullString `json:"push_to_start_token"`
	ApnsEnvironment       string         `json:"apns_environment"`
	NotificationsEnabled  int64          `json:"notifications_enabled"`
	LiveActivitiesEnabled int64          `json:"live_activities_enabled"`
}

func (q *Queries) FamilyNotificationDevices(ctx context.Context, familyID string) ([]FamilyNotificationDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, familyNotificationDevices, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FamilyNotificationDevicesRow{}
	for rows.Next() {
		var i FamilyNotificationDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ApnsToken,
			&i.PushToStartToken,
			&i.ApnsEnvironment,
			&i.NotificationsEnabled,
			&i.LiveActivitiesEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingLiveActivityTokens = `-- name: PendingLiveActivityTokens :one
select count(*) from live_activity_starts
left join live_activity_tokens
  on live_activity_starts.session_id=live_activity_tokens.session_id
  and live_activity_starts.device_id=live_activity_tokens.device_id
where live_activity_starts.session_id=?1
  and live_activity_tokens.token is null
`

func (q *Queries) PendingLiveActivityTokens(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, pendingLiveActivityTokens, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const registerLiveActivity = `-- name: RegisterLiveActivity :exec
insert into live_activity_tokens(session_id, device_id, token, apns_environment, updated_at)
values (?1, ?2, ?3, ?4, ?5)
on conflict(session_id, device_id) do update set
  token=excluded.token, apns_environment=excluded.apns_environment, updated_at=excluded.updated_at
`

type RegisterLiveActivityParams struct {
	SessionID       string `json:"session_id"`
	DeviceID        string `json:"device_id"`
	Token           string `json:"token"`
	ApnsEnvironment string `json:"apns_environment"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) RegisterLiveActivity(ctx context.Context, arg RegisterLiveActivityParams) error {
	_, err := q.db.ExecContext(ctx, registerLiveActivity,
		arg.SessionID,
		arg.DeviceID,
		arg.Token,
		arg.ApnsEnvironment,
		arg.UpdatedAt,
	)
	return err
}

const releaseLiveActivityStart = `-- name: ReleaseLiveActivityStart :exec
delete from live_activity_starts
where session_id=?1 and device_id=?2
  and push_to_start_token=?3
`

type ReleaseLiveActivityStartParams struct {
	SessionID        string `json:"session_id"`
	DeviceID         string `json:"device_id"`
	PushToStartToken string `json:"push_to_start_token"`
}

func (q *Queries) ReleaseLiveActivityStart(ctx context.Context, arg ReleaseLiveActivityStartParams) error {
	_, err := q.db.ExecContext(ctx, releaseLiveActivityStart, arg.SessionID, arg.DeviceID, arg.PushToStartToken)
	return err
}

const removeFamilyMemberships = `-- name: RemoveFamilyMemberships :exec
delete from family_members where user_id=?1
`

func (q *Queries) RemoveFamilyMemberships(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, removeFamilyMemberships, userID)
	return err
}

const sessionLiveActivityTokens = `-- name: SessionLiveActivityTokens :many
select live_activity_tokens.device_id, live_activity_tokens.token, live_activity_tokens.apns_environment
from live_activity_tokens
where live_activity_tokens.session_id=?1
`

type SessionLiveActivityTokensRow struct {
	DeviceID        string `json:"device_id"`
	Token           string `json:"token"`
	ApnsEnvironment string `json:"apns_environment"`
}

func (q *Queries) SessionLiveActivityTokens(ctx context.Context, sessionID string) ([]SessionLiveActivityTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, sessionLiveActivityTokens, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionLiveActivityTokensRow{}
	for rows.Next() {
		var i SessionLiveActivityTokensRow
		if err := rows.Scan(&i.DeviceID, &i.Token, &i.ApnsEnvironment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDeviceSession = `-- name: TouchDeviceSession :execrows
update devices set
  refresh_expires_at=?1,
  last_seen_at=?2
where id=?3 and refresh_token_hash=?4
`

type TouchDeviceSessionParams struct {
	RefreshExpiresAt sql.NullString `json:"refresh_expires_at"`
	LastSeenAt       string         `json:"last_seen_at"`
	ID               string         `json:"id"`
	RefreshTokenHash []byte         `json:"refresh_token_hash"`
}

func (q *Queries) TouchDeviceSession(ctx context.Context, arg TouchDeviceSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchDeviceSession,
		arg.RefreshExpiresAt,
		arg.LastSeenAt,
		arg.ID,
		arg.RefreshTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAppleRefreshToken = `-- name: UpdateAppleRefreshToken :exec
update users set apple_refresh_token_ciphertext=?1
where id=?2 and deleted_at is null
`

type UpdateAppleRefreshTokenParams struct {
	AppleRefreshTokenCiphertext []byte `json:"apple_refresh_token_ciphertext"`
	ID                          string `json:"id"`
}

func (q *Queries) UpdateAppleRefreshToken(ctx context.Context, arg UpdateAppleRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateAppleRefreshToken, arg.AppleRefreshTokenCiphertext, arg.ID)
	return err
}

const updateDevicePushSettings = `-- name: UpdateDevicePushSettings :execrows
update devices set
  apns_token=?1,
  push_to_start_token=?2,
  apns_environment=?3,
  notifications_enabled=?4,
  live_activities_enabled=?5,
  reminder_lead_minutes=?6,
  last_seen_at=?7
where id=?8 and user_id=?9
`

type UpdateDevicePushSettingsParams struct {
	ApnsToken             sql.NullString `json:"apns_token"`
	PushToStartToken      sql.NullString `json:"push_to_start_token"`
	ApnsEnvironment       string         `json:"apns_environment"`
	NotificationsEnabled  int64          `json:"notifications_enabled"`
	LiveActivitiesEnabled int64          `json:"live_activities_enabled"`
	ReminderLeadMinutes   int64          `json:"reminder_lead_minutes"`
	LastSeenAt            string         `json:"last_seen_at"`
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
}

func (q *Queries) UpdateDevicePushSettings(ctx context.Context, arg UpdateDevicePushSettingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDevicePushSettings,
		arg.ApnsToken,
		arg.PushToStartToken,
		arg.ApnsEnvironment,
		arg.NotificationsEnabled,
		arg.LiveActivitiesEnabled,
		arg.ReminderLeadMinutes,
		arg.LastSeenAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDevice = `-- name: UpsertDevice :exec
insert into devices(id, user_id, refresh_token_hash, refresh_expires_at, last_seen_at)
values (?1, ?2, ?3, ?4, ?5)
on conflict(id) do update set
  user_id=excluded.user_id,
  refresh_token_hash=excluded.refresh_token_hash,
  refresh_expires_at=excluded.refresh_expires_at,
  last_seen_at=excluded.last_seen_at
`

type UpsertDeviceParams struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	RefreshTokenHash []byte         `json:"refresh_token_hash"`
	RefreshExpiresAt sql.NullString `json:"refresh_expires_at"`
	LastSeenAt       string         `json:"last_seen_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.RefreshExpiresAt,
		arg.LastSeenAt,
	)
	return err
}

const userAppleRefreshToken = `-- name: UserAppleRefreshToken :one
select apple_refresh_token_ciphertext from users
where id=?1 and deleted_at is null
`

func (q *Queries) UserAppleRefreshToken(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, userAppleRefreshToken, id)
	var apple_refresh_token_ciphertext []byte
	err := row.Scan(&apple_refresh_token_ciphertext)
	return apple_refresh_token_ciphertext, err
}

const userIDByAppleSubject = `-- name: UserIDByAppleSubject :one
select id from users where apple_subject = ?1
`

func (q *Queries) UserIDByAppleSubject(ctx context.Context, appleSubject string) (string, error) {
	row := q.db.QueryRowContext(ctx, userIDByAppleSubject, appleSubject)
	var id string
	err := row.Scan(&id)
	return id, err
}
