// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: families.sql

package storedb

import (
	"context"
	"database/sql"
)

const activeFamilyMemberCount = `-- name: ActiveFamilyMemberCount :one
select count(*) from family_members
where family_id=?1 and removed_at is null
`

func (q *Queries) ActiveFamilyMemberCount(ctx context.Context, familyID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeFamilyMemberCount, familyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const activeFamilyMembers = `-- name: ActiveFamilyMembers :many
select fm.user_id, u.display_name, fm.role, fm.joined_at
from family_members as fm
join users as u on u.id=fm.user_id
where fm.family_id=?1 and fm.removed_at is null and u.deleted_at is null
order by case fm.role when 'owner' then 0 else 1 end, fm.joined_at, fm.user_id
`

type ActiveFamilyMembersRow struct {
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	JoinedAt    string `json:"joined_at"`
}

func (q *Queries) ActiveFamilyMembers(ctx context.Context, familyID string) ([]ActiveFamilyMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, activeFamilyMembers, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveFamilyMembersRow{}
	for rows.Next() {
		var i ActiveFamilyMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addCaregiver = `-- name: AddCaregiver :exec
insert into family_members(family_id, user_id, role, joined_at)
values (?1, ?2, 'caregiver', ?3)
on conflict(family_id, user_id) do update set
  removed_at=null,
  joined_at=excluded.joined_at
`

type AddCaregiverParams struct {
	FamilyID string `json:"family_id"`
	UserID   string `json:"user_id"`
	JoinedAt string `json:"joined_at"`
}

func (q *Queries) AddCaregiver(ctx context.Context, arg AddCaregiverParams) error {
	_, err := q.db.ExecContext(ctx, addCaregiver, arg.FamilyID, arg.UserID, arg.JoinedAt)
	return err
}

const addOwner = `-- name: AddOwner :exec
insert into family_members(family_id, user_id, role, joined_at)
values (?1, ?2, 'owner', ?3)
`

type AddOwnerParams struct {
	FamilyID string `json:"family_id"`
	UserID   string `json:"user_id"`
	JoinedAt string `json:"joined_at"`
}

func (q *Queries) AddOwner(ctx context.Context, arg AddOwnerParams) error {
	_, err := q.db.ExecContext(ctx, addOwner, arg.FamilyID, arg.UserID, arg.JoinedAt)
	return err
}

const claimInvite = `-- name: ClaimInvite :execrows
update invites set claimed_by=?1, claimed_at=?2
where id=?3 and claimed_at is null
`

type ClaimInviteParams struct {
	ClaimedBy sql.NullString `json:"claimed_by"`
	ClaimedAt sql.NullString `json:"claimed_at"`
	ID        string         `json:"id"`
}

func (q *Queries) ClaimInvite(ctx context.Context, arg ClaimInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimInvite, arg.ClaimedBy, arg.ClaimedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createFamily = `-- name: CreateFamily :exec
insert into families(id, name, owner_id, created_at)
values (?1, ?2, ?3, ?4)
`

type CreateFamilyParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	OwnerID   string `json:"owner_id"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) error {
	_, err := q.db.ExecContext(ctx, createFamily,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.CreatedAt,
	)
	return err
}

const createInvite = `-- name: CreateInvite :exec
insert into invites(id, family_id, token_hash, created_by, expires_at, created_at)
values (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateInviteParams struct {
	ID        string `json:"id"`
	FamilyID  string `json:"family_id"`
	TokenHash []byte `json:"token_hash"`
	CreatedBy string `json:"created_by"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.FamilyID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteFamilyOwnedBy = `-- name: DeleteFamilyOwnedBy :execrows
delete from families
where id=?1 and owner_id=?2
`

type DeleteFamilyOwnedByParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) DeleteFamilyOwnedBy(ctx context.Context, arg DeleteFamilyOwnedByParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFamilyOwnedBy, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSoleOwnerFamily = `-- name: DeleteSoleOwnerFamily :execrows
delete from families
where id=?1 and owner_id=?2
  and (select count(*) from family_members where family_id=?1 and removed_at is null)=1
`

type DeleteSoleOwnerFamilyParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) DeleteSoleOwnerFamily(ctx context.Context, arg DeleteSoleOwnerFamilyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSoleOwnerFamily, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const demoteFamilyOwner = `-- name: DemoteFamilyOwner :execrows
update family_members set role='caregiver'
where family_id=?1 and user_id=?2
  and role='owner' and removed_at is null
`

type DemoteFamilyOwnerParams struct {
	FamilyID string `json:"family_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) DemoteFamilyOwner(ctx context.Context, arg DemoteFamilyOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, demoteFamilyOwner, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const familiesForUser = `-- name: FamiliesForUser :many
select f.id, f.name, fm.role
from families as f
inner join family_members as fm on f.id=fm.family_id
where fm.user_id=?1 and fm.removed_at is null
order by fm.joined_at, f.id
`

type FamiliesForUserRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

func (q *Queries) FamiliesForUser(ctx context.Context, userID string) ([]FamiliesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, familiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FamiliesForUserRow{}
	for rows.Next() {
		var i FamiliesForUserRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const familyByID = `-- name: FamilyByID :one
select id, name, owner_id from families where id=?1
`

type FamilyByIDRow struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) FamilyByID(ctx context.Context, id string) (FamilyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, familyByID, id)
	var i FamilyByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const familyMemberRole = `-- name: FamilyMemberRole :one
select role from family_members
where family_id=?1 and user_id=?2 and removed_at is null
`

type FamilyMemberRoleParams struct {
	FamilyID string `json:"family_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) FamilyMemberRole(ctx context.Context, arg FamilyMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, familyMemberRole, arg.FamilyID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const familyOwnershipSuccessor = `-- name: FamilyOwnershipSuccessor :one
select user_id from family_members
where family_id=?1
  and user_id<>?2
  and removed_at is null
order by joined_at, user_id
limit 1
`

type FamilyOwnershipSuccessorParams struct {
	FamilyID string `json:"family_id"`
	OwnerID  string `json:"owner_id"`
}

func (q *Queries) FamilyOwnershipSuccessor(ctx context.Context, arg FamilyOwnershipSuccessorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, familyOwnershipSuccessor, arg.FamilyID, arg.OwnerID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const hasFamilyRole = `-- name: HasFamilyRole :one
select exists(
  select 1 from family_members
  where family_id=?1
    and user_id=?2
    and role=?3
    and removed_at is null
)
`

type HasFamilyRoleParams struct {
	FamilyID string `json:"family_id"`
	UserID   string `json:"user_id"`
	Role     string `json:"role"`
}

func (q *Queries) HasFamilyRole(ctx context.Context, arg HasFamilyRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasFamilyRole, arg.FamilyID, arg.UserID, arg.Role)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const inviteByTokenHash = `-- name: InviteByTokenHash :one
select id, family_id, expires_at, claimed_by, claimed_at
from invites
where token_hash=?1
`

type InviteByTokenHashRow struct {
	ID        string         `json:"id"`
	FamilyID  string         `json:"family_id"`
	ExpiresAt string         `json:"expires_at"`
	ClaimedBy sql.NullString `json:"claimed_by"`
	ClaimedAt sql.NullString `json:"claimed_at"`
}

func (q *Queries) InviteByTokenHash(ctx context.Context, tokenHash []byte) (InviteByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, inviteByTokenHash, tokenHash)
	var i InviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
	)
	return i, err
}

const isFamilyMember = `-- name: IsFamilyMember :one
select exists(
  select 1 from family_members
  where family_id=?1
    and user_id=?2
    and removed_at is null
)
`

type IsFamilyMemberParams struct {
	FamilyID string `json:"family_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) IsFamilyMember(ctx context.Context, arg IsFamilyMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFamilyMember, arg.FamilyID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ownedFamilyIDs = `-- name: OwnedFamilyIDs :many
select id from families
where owner_id=?1
order by created_at, id
`

func (q *Queries) OwnedFamilyIDs(ctx context.Context, ownerID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, ownedFamilyIDs, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingFamilyInvites = `-- name: PendingFamilyInvites :many
select id, expires_at, created_at from invites
where family_id=?1 and claimed_at is null and expires_at>?2
order by created_at desc, id
`

type PendingFamilyInvitesParams struct {
	FamilyID string `json:"family_id"`
	Now      string `json:"now"`
}

type PendingFamilyInvitesRow struct {
	ID        string `json:"id"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) PendingFamilyInvites(ctx context.Context, arg PendingFamilyInvitesParams) ([]PendingFamilyInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingFamilyInvites, arg.FamilyID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingFamilyInvitesRow{}
	for rows.Next() {
		var i PendingFamilyInvitesRow
		if err := rows.Scan(&i.ID, &i.ExpiresAt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteFamilyOwner = `-- name: PromoteFamilyOwner :execrows
update family_members set role='owner'
where family_id=?1
  and user_id=?2
  and removed_at is null
`

type PromoteFamilyOwnerParams struct {
	FamilyID string `json:"family_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) PromoteFamilyOwner(ctx context.Context, arg PromoteFamilyOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteFamilyOwner, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeCaregiver = `-- name: RemoveCaregiver :execrows
update family_members set removed_at=?1
where family_id=?2 and user_id=?3
  and role='caregiver' and removed_at is null
  and exists (select 1 from families where id=?2
    and (owner_id=?4 or ?4=?3))
`

type RemoveCaregiverParams struct {
	RemovedAt sql.NullString `json:"removed_at"`
	FamilyID  string         `json:"family_id"`
	UserID    string         `json:"user_id"`
	ActorID   string         `json:"actor_id"`
}

func (q *Queries) RemoveCaregiver(ctx context.Context, arg RemoveCaregiverParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeCaregiver,
		arg.RemovedAt,
		arg.FamilyID,
		arg.UserID,
		arg.ActorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameFamily = `-- name: RenameFamily :execrows
update families set name=?1
where id=?2 and owner_id=?3
`

type RenameFamilyParams struct {
	Name    string `json:"name"`
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) RenameFamily(ctx context.Context, arg RenameFamilyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameFamily, arg.Name, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokePendingInvite = `-- name: RevokePendingInvite :execrows
delete from invites as i where i.id=?1 and i.family_id=?2 and i.claimed_at is null
  and exists (select 1 from families as f where f.id=?2 and f.owner_id=?3)
`

type RevokePendingInviteParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
	OwnerID  string `json:"owner_id"`
}

func (q *Queries) RevokePendingInvite(ctx context.Context, arg RevokePendingInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokePendingInvite, arg.ID, arg.FamilyID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const transferFamilyOwnership = `-- name: TransferFamilyOwnership :execrows
update families set owner_id=?1
where id=?2 and owner_id=?3
`

type TransferFamilyOwnershipParams struct {
	SuccessorID string `json:"successor_id"`
	ID          string `json:"id"`
	OwnerID     string `json:"owner_id"`
}

func (q *Queries) TransferFamilyOwnership(ctx context.Context, arg TransferFamilyOwnershipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transferFamilyOwnership, arg.SuccessorID, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
