// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package storedb

import (
	"context"
	"database/sql"
)

const importSleep = `-- name: ImportSleep :execrows
insert into sleep_sessions(
  id, family_id, child_id, started_at, ended_at, revision,
  author_id, source, updated_at
) values (
  ?1, ?2, ?3,
  ?4, ?5, 1,
  ?6, 'history_import', ?7
)
on conflict(id) do nothing
`

type ImportSleepParams struct {
	ID        string         `json:"id"`
	FamilyID  string         `json:"family_id"`
	ChildID   string         `json:"child_id"`
	StartedAt string         `json:"started_at"`
	EndedAt   sql.NullString `json:"ended_at"`
	AuthorID  string         `json:"author_id"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) ImportSleep(ctx context.Context, arg ImportSleepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, importSleep,
		arg.ID,
		arg.FamilyID,
		arg.ChildID,
		arg.StartedAt,
		arg.EndedAt,
		arg.AuthorID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const importSleepContext = `-- name: ImportSleepContext :exec
update sleep_sessions set
  start_condition=?1,
  sleep_location=?2,
  end_condition=?3
where id=?4
`

type ImportSleepContextParams struct {
	StartCondition string `json:"start_condition"`
	SleepLocation  string `json:"sleep_location"`
	EndCondition   string `json:"end_condition"`
	ID             string `json:"id"`
}

func (q *Queries) ImportSleepContext(ctx context.Context, arg ImportSleepContextParams) error {
	_, err := q.db.ExecContext(ctx, importSleepContext,
		arg.StartCondition,
		arg.SleepLocation,
		arg.EndCondition,
		arg.ID,
	)
	return err
}

const importTarget = `-- name: ImportTarget :one
select c.family_id, fm.user_id
from children as c
inner join family_members as fm
  on c.family_id=fm.family_id
 and fm.user_id=?1
 and fm.removed_at is null
where c.id=?2
  and c.family_id=?3
  and c.deleted_at is null
`

type ImportTargetParams struct {
	AuthorID string `json:"author_id"`
	ChildID  string `json:"child_id"`
	FamilyID string `json:"family_id"`
}

type ImportTargetRow struct {
	FamilyID string `json:"family_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) ImportTarget(ctx context.Context, arg ImportTargetParams) (ImportTargetRow, error) {
	row := q.db.QueryRowContext(ctx, importTarget, arg.AuthorID, arg.ChildID, arg.FamilyID)
	var i ImportTargetRow
	err := row.Scan(&i.FamilyID, &i.UserID)
	return i, err
}
