// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
)

type Child struct {
	ID                     string         `json:"id"`
	FamilyID               string         `json:"family_id"`
	Nickname               string         `json:"nickname"`
	BirthDate              string         `json:"birth_date"`
	PredictionMode         string         `json:"prediction_mode"`
	ManualIntervalMinutes  sql.NullInt64  `json:"manual_interval_minutes"`
	QuietHoursStartMinutes int64          `json:"quiet_hours_start_minutes"`
	QuietHoursEndMinutes   int64          `json:"quiet_hours_end_minutes"`
	TimeZone               string         `json:"time_zone"`
	Revision               int64          `json:"revision"`
	UpdatedAt              string         `json:"updated_at"`
	DeletedAt              sql.NullString `json:"deleted_at"`
}

type Command struct {
	ID         string `json:"id"`
	FamilyID   string `json:"family_id"`
	UserID     string `json:"user_id"`
	Kind       string `json:"kind"`
	ResultJson []byte `json:"result_json"`
	CreatedAt  string `json:"created_at"`
}

type Delivery struct {
	ID          string         `json:"id"`
	FamilyID    string         `json:"family_id"`
	Kind        string         `json:"kind"`
	PayloadJson []byte         `json:"payload_json"`
	DueAt       string         `json:"due_at"`
	Attempts    int64          `json:"attempts"`
	Status      string         `json:"status"`
	LastError   sql.NullString `json:"last_error"`
	CreatedAt   string         `json:"created_at"`
}

type Device struct {
	ID                    string         `json:"id"`
	UserID                string         `json:"user_id"`
	RefreshTokenHash      []byte         `json:"refresh_token_hash"`
	RefreshExpiresAt      sql.NullString `json:"refresh_expires_at"`
	ApnsToken             sql.NullString `json:"apns_token"`
	PushToStartToken      sql.NullString `json:"push_to_start_token"`
	ApnsEnvironment       string         `json:"apns_environment"`
	NotificationsEnabled  int64          `json:"notifications_enabled"`
	LiveActivitiesEnabled int64          `json:"live_activities_enabled"`
	ReminderLeadMinutes   int64          `json:"reminder_lead_minutes"`
	LastSeenAt            string         `json:"last_seen_at"`
}

type Family struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	OwnerID   string `json:"owner_id"`
	CreatedAt string `json:"created_at"`
}

type FamilyMember struct {
	FamilyID  string         `json:"family_id"`
	UserID    string         `json:"user_id"`
	Role      string         `json:"role"`
	JoinedAt  string         `json:"joined_at"`
	RemovedAt sql.NullString `json:"removed_at"`
}

type FamilySyncSnapshot struct {
	FamilyID     string `json:"family_id"`
	Generation   string `json:"generation"`
	Cursor       int64  `json:"cursor"`
	EntitiesJson []byte `json:"entities_json"`
	CreatedAt    string `json:"created_at"`
}

type Invite struct {
	ID        string         `json:"id"`
	FamilyID  string         `json:"family_id"`
	TokenHash []byte         `json:"token_hash"`
	CreatedBy string         `json:"created_by"`
	ExpiresAt string         `json:"expires_at"`
	ClaimedBy sql.NullString `json:"claimed_by"`
	ClaimedAt sql.NullString `json:"claimed_at"`
	CreatedAt string         `json:"created_at"`
}

type LiveActivityStart struct {
	SessionID        string `json:"session_id"`
	DeviceID         string `json:"device_id"`
	PushToStartToken string `json:"push_to_start_token"`
	CreatedAt        string `json:"created_at"`
}

type LiveActivityToken struct {
	SessionID       string `json:"session_id"`
	DeviceID        string `json:"device_id"`
	Token           string `json:"token"`
	ApnsEnvironment string `json:"apns_environment"`
	UpdatedAt       string `json:"updated_at"`
}

type SleepSession struct {
	ID                  string         `json:"id"`
	FamilyID            string         `json:"family_id"`
	ChildID             string         `json:"child_id"`
	StartedAt           string         `json:"started_at"`
	EndedAt             sql.NullString `json:"ended_at"`
	Revision            int64          `json:"revision"`
	AuthorID            string         `json:"author_id"`
	Source              string         `json:"source"`
	StartCondition      string         `json:"start_condition"`
	SleepLocation       string         `json:"sleep_location"`
	EndCondition        string         `json:"end_condition"`
	WakeMood            string         `json:"wake_mood"`
	WakeReason          string         `json:"wake_reason"`
	CaregiverIntervened sql.NullInt64  `json:"caregiver_intervened"`
	SupersededByID      sql.NullString `json:"superseded_by_id"`
	UpdatedAt           string         `json:"updated_at"`
	DeletedAt           sql.NullString `json:"deleted_at"`
}

type SyncEvent struct {
	Cursor      int64  `json:"cursor"`
	FamilyID    string `json:"family_id"`
	EntityType  string `json:"entity_type"`
	EntityID    string `json:"entity_id"`
	Operation   string `json:"operation"`
	Revision    int64  `json:"revision"`
	PayloadJson []byte `json:"payload_json"`
	CreatedAt   string `json:"created_at"`
}

type User struct {
	ID                          string         `json:"id"`
	AppleSubject                string         `json:"apple_subject"`
	DisplayName                 string         `json:"display_name"`
	AppleRefreshTokenCiphertext []byte         `json:"apple_refresh_token_ciphertext"`
	CreatedAt                   string         `json:"created_at"`
	DeletedAt                   sql.NullString `json:"deleted_at"`
}
