// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"context"
)

type Querier interface {
	ActiveDeviceSession(ctx context.Context, arg ActiveDeviceSessionParams) (bool, error)
	ActiveSleepByID(ctx context.Context, arg ActiveSleepByIDParams) (ActiveSleepByIDRow, error)
	ActiveSleepForChild(ctx context.Context, arg ActiveSleepForChildParams) (string, error)
	ActiveSleepForFamily(ctx context.Context, familyID string) (ActiveSleepForFamilyRow, error)
	ActiveSleepsMissingFromDevice(ctx context.Context, deviceID string) ([]ActiveSleepsMissingFromDeviceRow, error)
	AddCaregiver(ctx context.Context, arg AddCaregiverParams) error
	AddOwner(ctx context.Context, arg AddOwnerParams) error
	AnonymizeUser(ctx context.Context, arg AnonymizeUserParams) (int64, error)
	AppendEvent(ctx context.Context, arg AppendEventParams) error
	AppleRefreshTokens(ctx context.Context) ([]AppleRefreshTokensRow, error)
	CanRegisterLiveActivity(ctx context.Context, arg CanRegisterLiveActivityParams) (bool, error)
	ChildNotificationContext(ctx context.Context, arg ChildNotificationContextParams) (ChildNotificationContextRow, error)
	ChildRecord(ctx context.Context, arg ChildRecordParams) (ChildRecordRow, error)
	ChildRevision(ctx context.Context, arg ChildRevisionParams) (int64, error)
	ClaimInvite(ctx context.Context, arg ClaimInviteParams) (int64, error)
	ClaimLiveActivityStart(ctx context.Context, arg ClaimLiveActivityStartParams) (int64, error)
	CommandResult(ctx context.Context, arg CommandResultParams) ([]byte, error)
	CreateActiveSleep(ctx context.Context, arg CreateActiveSleepParams) error
	CreateChild(ctx context.Context, arg CreateChildParams) error
	CreateFamily(ctx context.Context, arg CreateFamilyParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreateSleep(ctx context.Context, arg CreateSleepParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteDeviceForUser(ctx context.Context, arg DeleteDeviceForUserParams) (int64, error)
	DeleteFamilyEventsThrough(ctx context.Context, arg DeleteFamilyEventsThroughParams) error
	DeleteFamilyOwnedBy(ctx context.Context, arg DeleteFamilyOwnedByParams) (int64, error)
	DeleteLiveActivityToken(ctx context.Context, token string) error
	DeleteLiveActivityTokens(ctx context.Context, sessionID string) error
	DeletePushToStartToken(ctx context.Context, arg DeletePushToStartTokenParams) error
	DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error
	DeleteSentDeliveriesBefore(ctx context.Context, createdAt string) (int64, error)
	DeleteSleep(ctx context.Context, arg DeleteSleepParams) error
	DeleteUserDevices(ctx context.Context, userID string) error
	DevicePushSettings(ctx context.Context, arg DevicePushSettingsParams) (DevicePushSettingsRow, error)
	DeviceSession(ctx context.Context, id string) (DeviceSessionRow, error)
	DueDeliveries(ctx context.Context, arg DueDeliveriesParams) ([]DueDeliveriesRow, error)
	EndSleep(ctx context.Context, arg EndSleepParams) error
	ExistingSleepRevision(ctx context.Context, arg ExistingSleepRevisionParams) (int64, error)
	FamiliesForUser(ctx context.Context, userID string) ([]FamiliesForUserRow, error)
	FamilyByID(ctx context.Context, id string) (FamilyByIDRow, error)
	FamilyEventCount(ctx context.Context, familyID string) (int64, error)
	FamilyNotificationDevices(ctx context.Context, familyID string) ([]FamilyNotificationDevicesRow, error)
	FamilyOwnershipSuccessor(ctx context.Context, arg FamilyOwnershipSuccessorParams) (string, error)
	FamilySyncSnapshot(ctx context.Context, familyID string) (FamilySyncSnapshotRow, error)
	HasFamilyRole(ctx context.Context, arg HasFamilyRoleParams) (bool, error)
	ImportSleep(ctx context.Context, arg ImportSleepParams) (int64, error)
	ImportSleepContext(ctx context.Context, arg ImportSleepContextParams) error
	ImportTarget(ctx context.Context, arg ImportTargetParams) (ImportTargetRow, error)
	InviteByTokenHash(ctx context.Context, tokenHash []byte) (InviteByTokenHashRow, error)
	IsFamilyMember(ctx context.Context, arg IsFamilyMemberParams) (bool, error)
	LatestFamilyCursor(ctx context.Context, familyID string) (int64, error)
	MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error
	MarkDeliverySending(ctx context.Context, id string) (int64, error)
	MarkDeliverySent(ctx context.Context, id string) error
	MergeSleep(ctx context.Context, arg MergeSleepParams) error
	OwnedFamilyIDs(ctx context.Context, ownerID string) ([]string, error)
	PendingLiveActivityTokens(ctx context.Context, sessionID string) (int64, error)
	PredictionChild(ctx context.Context, familyID string) (PredictionChildRow, error)
	PromoteFamilyOwner(ctx context.Context, arg PromoteFamilyOwnerParams) (int64, error)
	QueueDelivery(ctx context.Context, arg QueueDeliveryParams) error
	ReadEvents(ctx context.Context, arg ReadEventsParams) ([]ReadEventsRow, error)
	RecordCommand(ctx context.Context, arg RecordCommandParams) error
	RegisterLiveActivity(ctx context.Context, arg RegisterLiveActivityParams) error
	ReleaseLiveActivityStart(ctx context.Context, arg ReleaseLiveActivityStartParams) error
	RemoveFamilyMemberships(ctx context.Context, userID string) error
	ResetSendingDeliveries(ctx context.Context) error
	SessionLiveActivityTokens(ctx context.Context, sessionID string) ([]SessionLiveActivityTokensRow, error)
	SleepIntervals(ctx context.Context, arg SleepIntervalsParams) ([]SleepIntervalsRow, error)
	SleepRecord(ctx context.Context, arg SleepRecordParams) (SleepSession, error)
	SleepRevision(ctx context.Context, arg SleepRevisionParams) (int64, error)
	SnapshotChildIDs(ctx context.Context, familyID string) ([]string, error)
	SnapshotSleepIDs(ctx context.Context, familyID string) ([]string, error)
	SupersedeSleep(ctx context.Context, arg SupersedeSleepParams) error
	SweetSpotHistory(ctx context.Context, childID string) ([]SweetSpotHistoryRow, error)
	TouchDeviceSession(ctx context.Context, arg TouchDeviceSessionParams) (int64, error)
	TransferFamilyOwnership(ctx context.Context, arg TransferFamilyOwnershipParams) (int64, error)
	UpdateAppleRefreshToken(ctx context.Context, arg UpdateAppleRefreshTokenParams) error
	UpdateChild(ctx context.Context, arg UpdateChildParams) error
	UpdateDevicePushSettings(ctx context.Context, arg UpdateDevicePushSettingsParams) (int64, error)
	UpdateSleep(ctx context.Context, arg UpdateSleepParams) error
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error
	UpsertFamilySyncSnapshot(ctx context.Context, arg UpsertFamilySyncSnapshotParams) error
	UserAppleRefreshToken(ctx context.Context, id string) ([]byte, error)
	UserIDByAppleSubject(ctx context.Context, appleSubject string) (string, error)
}

var _ Querier = (*Queries)(nil)
