// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package storedb

import (
	"context"
	"database/sql"
)

const cancelPendingSleepReminders = `-- name: CancelPendingSleepReminders :exec
update sleep_reminders set status='cancelled' where status='pending'
`

func (q *Queries) CancelPendingSleepReminders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cancelPendingSleepReminders)
	return err
}

const cancelSleepReminder = `-- name: CancelSleepReminder :exec
update sleep_reminders set status='cancelled'
where device_id=?1 and child_id=?2
  and sleep_id=?3 and status='pending'
`

type CancelSleepReminderParams struct {
	DeviceID string `json:"device_id"`
	ChildID  string `json:"child_id"`
	SleepID  string `json:"sleep_id"`
}

func (q *Queries) CancelSleepReminder(ctx context.Context, arg CancelSleepReminderParams) error {
	_, err := q.db.ExecContext(ctx, cancelSleepReminder, arg.DeviceID, arg.ChildID, arg.SleepID)
	return err
}

const claimSleepReminder = `-- name: ClaimSleepReminder :execrows
update sleep_reminders set status='attempted'
where device_id=?1 and child_id=?2
  and sleep_id=?3 and status='pending'
`

type ClaimSleepReminderParams struct {
	DeviceID string `json:"device_id"`
	ChildID  string `json:"child_id"`
	SleepID  string `json:"sleep_id"`
}

func (q *Queries) ClaimSleepReminder(ctx context.Context, arg ClaimSleepReminderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimSleepReminder, arg.DeviceID, arg.ChildID, arg.SleepID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOldSleepReminders = `-- name: DeleteOldSleepReminders :exec
delete from sleep_reminders where due_at<?1
`

func (q *Queries) DeleteOldSleepReminders(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, deleteOldSleepReminders, cutoff)
	return err
}

const dueSleepReminders = `-- name: DueSleepReminders :many
select device_id, child_id, family_id, sleep_id, target_at, due_at
from sleep_reminders where status='pending' and due_at<=?1
order by due_at limit 20
`

type DueSleepRemindersRow struct {
	DeviceID string `json:"device_id"`
	ChildID  string `json:"child_id"`
	FamilyID string `json:"family_id"`
	SleepID  string `json:"sleep_id"`
	TargetAt string `json:"target_at"`
	DueAt    string `json:"due_at"`
}

func (q *Queries) DueSleepReminders(ctx context.Context, now string) ([]DueSleepRemindersRow, error) {
	rows, err := q.db.QueryContext(ctx, dueSleepReminders, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueSleepRemindersRow{}
	for rows.Next() {
		var i DueSleepRemindersRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.ChildID,
			&i.FamilyID,
			&i.SleepID,
			&i.TargetAt,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reminderAnchor = `-- name: ReminderAnchor :one
select id from sleep_sessions
where child_id=?1 and ended_at is not null
  and deleted_at is null and superseded_by_id is null
order by started_at desc limit 1
`

func (q *Queries) ReminderAnchor(ctx context.Context, childID string) (string, error) {
	row := q.db.QueryRowContext(ctx, reminderAnchor, childID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const reminderCandidates = `-- name: ReminderCandidates :many
select devices.id as device_id, devices.apns_token, devices.apns_environment,
  devices.reminder_lead_minutes, devices.remote_reminders_until, devices.remote_reminders_from, devices.notification_language,
  children.id as child_id, children.family_id, children.birth_date, children.prediction_mode,
  children.manual_interval_minutes, children.time_zone
from devices
inner join family_members on devices.user_id=family_members.user_id
inner join children on family_members.family_id=children.family_id
where family_members.removed_at is null and children.deleted_at is null
  and devices.notifications_enabled=1 and devices.apns_token is not null
  and devices.remote_reminders_until>?1
`

type ReminderCandidatesRow struct {
	DeviceID              string         `json:"device_id"`
	ApnsToken             sql.NullString `json:"apns_token"`
	ApnsEnvironment       string         `json:"apns_environment"`
	ReminderLeadMinutes   int64          `json:"reminder_lead_minutes"`
	RemoteRemindersUntil  sql.NullString `json:"remote_reminders_until"`
	RemoteRemindersFrom   sql.NullString `json:"remote_reminders_from"`
	NotificationLanguage  string         `json:"notification_language"`
	ChildID               string         `json:"child_id"`
	FamilyID              string         `json:"family_id"`
	BirthDate             string         `json:"birth_date"`
	PredictionMode        string         `json:"prediction_mode"`
	ManualIntervalMinutes sql.NullInt64  `json:"manual_interval_minutes"`
	TimeZone              string         `json:"time_zone"`
}

func (q *Queries) ReminderCandidates(ctx context.Context, now sql.NullString) ([]ReminderCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, reminderCandidates, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReminderCandidatesRow{}
	for rows.Next() {
		var i ReminderCandidatesRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.ApnsToken,
			&i.ApnsEnvironment,
			&i.ReminderLeadMinutes,
			&i.RemoteRemindersUntil,
			&i.RemoteRemindersFrom,
			&i.NotificationLanguage,
			&i.ChildID,
			&i.FamilyID,
			&i.BirthDate,
			&i.PredictionMode,
			&i.ManualIntervalMinutes,
			&i.TimeZone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSleepReminder = `-- name: UpsertSleepReminder :exec
insert into sleep_reminders (device_id, child_id, family_id, sleep_id, target_at, due_at, created_at)
values (?1, ?2, ?3, ?4,
  ?5, ?6, ?7)
on conflict (device_id, child_id, sleep_id) do update
set target_at=excluded.target_at, due_at=excluded.due_at, status='pending'
where sleep_reminders.status!='attempted'
`

type UpsertSleepReminderParams struct {
	DeviceID  string `json:"device_id"`
	ChildID   string `json:"child_id"`
	FamilyID  string `json:"family_id"`
	SleepID   string `json:"sleep_id"`
	TargetAt  string `json:"target_at"`
	DueAt     string `json:"due_at"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) UpsertSleepReminder(ctx context.Context, arg UpsertSleepReminderParams) error {
	_, err := q.db.ExecContext(ctx, upsertSleepReminder,
		arg.DeviceID,
		arg.ChildID,
		arg.FamilyID,
		arg.SleepID,
		arg.TargetAt,
		arg.DueAt,
		arg.CreatedAt,
	)
	return err
}
