// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package storedb

import (
	"context"
	"database/sql"
)

const activeSleepForChild = `-- name: ActiveSleepForChild :one
select id from sleep_sessions
where family_id=?1
  and child_id=?2
  and ended_at is null
  and deleted_at is null
  and superseded_by_id is null
order by started_at, id limit 1
`

type ActiveSleepForChildParams struct {
	FamilyID string `json:"family_id"`
	ChildID  string `json:"child_id"`
}

func (q *Queries) ActiveSleepForChild(ctx context.Context, arg ActiveSleepForChildParams) (string, error) {
	row := q.db.QueryRowContext(ctx, activeSleepForChild, arg.FamilyID, arg.ChildID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const activeSleepForFamily = `-- name: ActiveSleepForFamily :one
select id, started_at, revision from sleep_sessions
where family_id=?1
  and ended_at is null
  and deleted_at is null
  and superseded_by_id is null
order by started_at limit 1
`

type ActiveSleepForFamilyRow struct {
	ID        string `json:"id"`
	StartedAt string `json:"started_at"`
	Revision  int64  `json:"revision"`
}

func (q *Queries) ActiveSleepForFamily(ctx context.Context, familyID string) (ActiveSleepForFamilyRow, error) {
	row := q.db.QueryRowContext(ctx, activeSleepForFamily, familyID)
	var i ActiveSleepForFamilyRow
	err := row.Scan(&i.ID, &i.StartedAt, &i.Revision)
	return i, err
}

const appendEvent = `-- name: AppendEvent :exec
insert into sync_events(
  family_id, entity_type, entity_id, operation, revision, payload_json, created_at
) values (
  ?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7
)
`

type AppendEventParams struct {
	FamilyID    string `json:"family_id"`
	EntityType  string `json:"entity_type"`
	EntityID    string `json:"entity_id"`
	Operation   string `json:"operation"`
	Revision    int64  `json:"revision"`
	PayloadJson []byte `json:"payload_json"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.FamilyID,
		arg.EntityType,
		arg.EntityID,
		arg.Operation,
		arg.Revision,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	return err
}

const childRecord = `-- name: ChildRecord :one
select id, family_id, nickname, birth_date, prediction_mode,
  manual_interval_minutes, quiet_hours_start_minutes,
  quiet_hours_end_minutes, time_zone, growth_reference, revision, updated_at, deleted_at
from children
where id=?1 and family_id=?2
`

type ChildRecordParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) ChildRecord(ctx context.Context, arg ChildRecordParams) (Child, error) {
	row := q.db.QueryRowContext(ctx, childRecord, arg.ID, arg.FamilyID)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Nickname,
		&i.BirthDate,
		&i.PredictionMode,
		&i.ManualIntervalMinutes,
		&i.QuietHoursStartMinutes,
		&i.QuietHoursEndMinutes,
		&i.TimeZone,
		&i.GrowthReference,
		&i.Revision,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const childRevision = `-- name: ChildRevision :one
select revision from children
where id=?1 and family_id=?2 and deleted_at is null
`

type ChildRevisionParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) ChildRevision(ctx context.Context, arg ChildRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, childRevision, arg.ID, arg.FamilyID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const commandResult = `-- name: CommandResult :one
select result_json from commands
where id=?1 and family_id=?2
`

type CommandResultParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) CommandResult(ctx context.Context, arg CommandResultParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, commandResult, arg.ID, arg.FamilyID)
	var result_json []byte
	err := row.Scan(&result_json)
	return result_json, err
}

const createActiveSleep = `-- name: CreateActiveSleep :exec
insert into sleep_sessions(
  id, family_id, child_id, started_at, ended_at, recorded_started_at, recorded_ended_at, revision,
  author_id, source, start_condition, sleep_location, end_condition,
  wake_mood, wake_reason, caregiver_intervened, updated_at
) values (
  ?1, ?2, ?3,
  ?4, null, ?4, null, 1, ?5,
  ?6, ?7, ?8,
  ?9, ?10, ?11,
  ?12, ?13
)
`

type CreateActiveSleepParams struct {
	ID                  string        `json:"id"`
	FamilyID            string        `json:"family_id"`
	ChildID             string        `json:"child_id"`
	StartedAt           string        `json:"started_at"`
	AuthorID            string        `json:"author_id"`
	Source              string        `json:"source"`
	StartCondition      string        `json:"start_condition"`
	SleepLocation       string        `json:"sleep_location"`
	EndCondition        string        `json:"end_condition"`
	WakeMood            string        `json:"wake_mood"`
	WakeReason          string        `json:"wake_reason"`
	CaregiverIntervened sql.NullInt64 `json:"caregiver_intervened"`
	UpdatedAt           string        `json:"updated_at"`
}

func (q *Queries) CreateActiveSleep(ctx context.Context, arg CreateActiveSleepParams) error {
	_, err := q.db.ExecContext(ctx, createActiveSleep,
		arg.ID,
		arg.FamilyID,
		arg.ChildID,
		arg.StartedAt,
		arg.AuthorID,
		arg.Source,
		arg.StartCondition,
		arg.SleepLocation,
		arg.EndCondition,
		arg.WakeMood,
		arg.WakeReason,
		arg.CaregiverIntervened,
		arg.UpdatedAt,
	)
	return err
}

const createChild = `-- name: CreateChild :exec
insert into children(
  id, family_id, nickname, birth_date, prediction_mode,
  manual_interval_minutes, quiet_hours_start_minutes,
  quiet_hours_end_minutes, time_zone, growth_reference, revision, updated_at
) values (
  ?1, ?2, ?3, ?4,
  ?5, ?6,
  ?7, ?8, ?9, ?10, 1,
  ?11
)
`

type CreateChildParams struct {
	ID                     string        `json:"id"`
	FamilyID               string        `json:"family_id"`
	Nickname               string        `json:"nickname"`
	BirthDate              string        `json:"birth_date"`
	PredictionMode         string        `json:"prediction_mode"`
	ManualIntervalMinutes  sql.NullInt64 `json:"manual_interval_minutes"`
	QuietHoursStartMinutes int64         `json:"quiet_hours_start_minutes"`
	QuietHoursEndMinutes   int64         `json:"quiet_hours_end_minutes"`
	TimeZone               string        `json:"time_zone"`
	GrowthReference        string        `json:"growth_reference"`
	UpdatedAt              string        `json:"updated_at"`
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) error {
	_, err := q.db.ExecContext(ctx, createChild,
		arg.ID,
		arg.FamilyID,
		arg.Nickname,
		arg.BirthDate,
		arg.PredictionMode,
		arg.ManualIntervalMinutes,
		arg.QuietHoursStartMinutes,
		arg.QuietHoursEndMinutes,
		arg.TimeZone,
		arg.GrowthReference,
		arg.UpdatedAt,
	)
	return err
}

const createGrowthMeasurement = `-- name: CreateGrowthMeasurement :exec
insert into growth_measurements(
  id, family_id, child_id, measured_at, weight_grams, height_millimeters,
  note, revision, updated_at
) values (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, 1,
  ?8
)
`

type CreateGrowthMeasurementParams struct {
	ID                string        `json:"id"`
	FamilyID          string        `json:"family_id"`
	ChildID           string        `json:"child_id"`
	MeasuredAt        string        `json:"measured_at"`
	WeightGrams       sql.NullInt64 `json:"weight_grams"`
	HeightMillimeters sql.NullInt64 `json:"height_millimeters"`
	Note              string        `json:"note"`
	UpdatedAt         string        `json:"updated_at"`
}

func (q *Queries) CreateGrowthMeasurement(ctx context.Context, arg CreateGrowthMeasurementParams) error {
	_, err := q.db.ExecContext(ctx, createGrowthMeasurement,
		arg.ID,
		arg.FamilyID,
		arg.ChildID,
		arg.MeasuredAt,
		arg.WeightGrams,
		arg.HeightMillimeters,
		arg.Note,
		arg.UpdatedAt,
	)
	return err
}

const createGrowthReferencePoint = `-- name: CreateGrowthReferencePoint :exec
insert into growth_reference_points(reference, metric, age_months, sd, value)
values (?1, ?2, ?3, ?4, ?5)
`

type CreateGrowthReferencePointParams struct {
	Reference string `json:"reference"`
	Metric    string `json:"metric"`
	AgeMonths int64  `json:"age_months"`
	Sd        int64  `json:"sd"`
	Value     int64  `json:"value"`
}

func (q *Queries) CreateGrowthReferencePoint(ctx context.Context, arg CreateGrowthReferencePointParams) error {
	_, err := q.db.ExecContext(ctx, createGrowthReferencePoint,
		arg.Reference,
		arg.Metric,
		arg.AgeMonths,
		arg.Sd,
		arg.Value,
	)
	return err
}

const createSleep = `-- name: CreateSleep :exec
insert into sleep_sessions(
  id, family_id, child_id, started_at, ended_at, recorded_started_at, recorded_ended_at, revision,
  author_id, source, start_condition, sleep_location, end_condition,
  wake_mood, wake_reason, caregiver_intervened, updated_at
) values (
  ?1, ?2, ?3,
  ?4, ?5, ?4, ?5, 1, ?6,
  ?7, ?8, ?9,
  ?10, ?11, ?12,
  ?13, ?14
)
`

type CreateSleepParams struct {
	ID                  string         `json:"id"`
	FamilyID            string         `json:"family_id"`
	ChildID             string         `json:"child_id"`
	StartedAt           string         `json:"started_at"`
	EndedAt             sql.NullString `json:"ended_at"`
	AuthorID            string         `json:"author_id"`
	Source              string         `json:"source"`
	StartCondition      string         `json:"start_condition"`
	SleepLocation       string         `json:"sleep_location"`
	EndCondition        string         `json:"end_condition"`
	WakeMood            string         `json:"wake_mood"`
	WakeReason          string         `json:"wake_reason"`
	CaregiverIntervened sql.NullInt64  `json:"caregiver_intervened"`
	UpdatedAt           string         `json:"updated_at"`
}

func (q *Queries) CreateSleep(ctx context.Context, arg CreateSleepParams) error {
	_, err := q.db.ExecContext(ctx, createSleep,
		arg.ID,
		arg.FamilyID,
		arg.ChildID,
		arg.StartedAt,
		arg.EndedAt,
		arg.AuthorID,
		arg.Source,
		arg.StartCondition,
		arg.SleepLocation,
		arg.EndCondition,
		arg.WakeMood,
		arg.WakeReason,
		arg.CaregiverIntervened,
		arg.UpdatedAt,
	)
	return err
}

const createTemperatureReading = `-- name: CreateTemperatureReading :exec
insert into temperature_readings(id, family_id, child_id, measured_at, centi_celsius, note, revision, updated_at)
values (?1, ?2, ?3, ?4, ?5, ?6, 1, ?7)
`

type CreateTemperatureReadingParams struct {
	ID           string `json:"id"`
	FamilyID     string `json:"family_id"`
	ChildID      string `json:"child_id"`
	MeasuredAt   string `json:"measured_at"`
	CentiCelsius int64  `json:"centi_celsius"`
	Note         string `json:"note"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) CreateTemperatureReading(ctx context.Context, arg CreateTemperatureReadingParams) error {
	_, err := q.db.ExecContext(ctx, createTemperatureReading,
		arg.ID,
		arg.FamilyID,
		arg.ChildID,
		arg.MeasuredAt,
		arg.CentiCelsius,
		arg.Note,
		arg.UpdatedAt,
	)
	return err
}

const deleteChild = `-- name: DeleteChild :execrows
update children set deleted_at=?1, updated_at=?2, revision=revision+1
where id=?3 and family_id=?4 and deleted_at is null
`

type DeleteChildParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
	FamilyID  string         `json:"family_id"`
}

func (q *Queries) DeleteChild(ctx context.Context, arg DeleteChildParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChild,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFamilyEventsThrough = `-- name: DeleteFamilyEventsThrough :exec
delete from sync_events
where family_id=?1 and cursor<=?2
`

type DeleteFamilyEventsThroughParams struct {
	FamilyID string `json:"family_id"`
	Cursor   int64  `json:"cursor"`
}

func (q *Queries) DeleteFamilyEventsThrough(ctx context.Context, arg DeleteFamilyEventsThroughParams) error {
	_, err := q.db.ExecContext(ctx, deleteFamilyEventsThrough, arg.FamilyID, arg.Cursor)
	return err
}

const deleteGrowthMeasurement = `-- name: DeleteGrowthMeasurement :exec
update growth_measurements set
  deleted_at=?1,
  revision=?2,
  updated_at=?3
where id=?4 and family_id=?5
`

type DeleteGrowthMeasurementParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	Revision  int64          `json:"revision"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
	FamilyID  string         `json:"family_id"`
}

func (q *Queries) DeleteGrowthMeasurement(ctx context.Context, arg DeleteGrowthMeasurementParams) error {
	_, err := q.db.ExecContext(ctx, deleteGrowthMeasurement,
		arg.DeletedAt,
		arg.Revision,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	return err
}

const deleteGrowthReferencePoints = `-- name: DeleteGrowthReferencePoints :exec
delete from growth_reference_points
`

func (q *Queries) DeleteGrowthReferencePoints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteGrowthReferencePoints)
	return err
}

const deleteSentDeliveriesBefore = `-- name: DeleteSentDeliveriesBefore :execrows
delete from deliveries
where status='sent' and created_at<?1
`

func (q *Queries) DeleteSentDeliveriesBefore(ctx context.Context, createdAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSentDeliveriesBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSleep = `-- name: DeleteSleep :exec
update sleep_sessions set
  deleted_at=?1,
  revision=?2,
  updated_at=?3
where id=?4
`

type DeleteSleepParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	Revision  int64          `json:"revision"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeleteSleep(ctx context.Context, arg DeleteSleepParams) error {
	_, err := q.db.ExecContext(ctx, deleteSleep,
		arg.DeletedAt,
		arg.Revision,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const deleteTemperatureReading = `-- name: DeleteTemperatureReading :exec
update temperature_readings set deleted_at=?1, revision=?2, updated_at=?3
where id=?4 and family_id=?5
`

type DeleteTemperatureReadingParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	Revision  int64          `json:"revision"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
	FamilyID  string         `json:"family_id"`
}

func (q *Queries) DeleteTemperatureReading(ctx context.Context, arg DeleteTemperatureReadingParams) error {
	_, err := q.db.ExecContext(ctx, deleteTemperatureReading,
		arg.DeletedAt,
		arg.Revision,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	return err
}

const dueDeliveries = `-- name: DueDeliveries :many
select id, family_id, kind, payload_json, due_at, attempts
from deliveries
where status in ('pending', 'failed') and due_at<=?1
order by due_at, created_at
limit ?2
`

type DueDeliveriesParams struct {
	Now         string `json:"now"`
	ResultLimit int64  `json:"result_limit"`
}

type DueDeliveriesRow struct {
	ID          string `json:"id"`
	FamilyID    string `json:"family_id"`
	Kind        string `json:"kind"`
	PayloadJson []byte `json:"payload_json"`
	DueAt       string `json:"due_at"`
	Attempts    int64  `json:"attempts"`
}

func (q *Queries) DueDeliveries(ctx context.Context, arg DueDeliveriesParams) ([]DueDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, dueDeliveries, arg.Now, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueDeliveriesRow{}
	for rows.Next() {
		var i DueDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Kind,
			&i.PayloadJson,
			&i.DueAt,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const duplicateStartCandidate = `-- name: DuplicateStartCandidate :one
select id, coalesce(superseded_by_id, id) as presented_id from sleep_sessions
where family_id=?1
  and child_id=?2
  and deleted_at is null
  and recorded_started_at >= cast(?3 as text)
  and recorded_started_at <= cast(?4 as text)
  and (recorded_ended_at is null or recorded_ended_at > cast(?5 as text))
order by recorded_started_at, id
limit 1
`

type DuplicateStartCandidateParams struct {
	FamilyID    string `json:"family_id"`
	ChildID     string `json:"child_id"`
	WindowStart string `json:"window_start"`
	WindowEnd   string `json:"window_end"`
	StartedAt   string `json:"started_at"`
}

type DuplicateStartCandidateRow struct {
	ID          string `json:"id"`
	PresentedID string `json:"presented_id"`
}

// A second tap for the same sleep: a session starting within the duplicate
// window that had not ended by the new start, whether or not it has ended since
// (after a restore its end can be replayed before the duplicate start).
func (q *Queries) DuplicateStartCandidate(ctx context.Context, arg DuplicateStartCandidateParams) (DuplicateStartCandidateRow, error) {
	row := q.db.QueryRowContext(ctx, duplicateStartCandidate,
		arg.FamilyID,
		arg.ChildID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.StartedAt,
	)
	var i DuplicateStartCandidateRow
	err := row.Scan(&i.ID, &i.PresentedID)
	return i, err
}

const endSleep = `-- name: EndSleep :exec
update sleep_sessions set
  recorded_ended_at=?1,
  ended_at=?1,
  end_condition=?2,
  wake_mood=?3,
  wake_reason=?4,
  caregiver_intervened=?5,
  revision=revision+1,
  updated_at=?6
where id=?7 and family_id=?8
`

type EndSleepParams struct {
	EndedAt             sql.NullString `json:"ended_at"`
	EndCondition        string         `json:"end_condition"`
	WakeMood            string         `json:"wake_mood"`
	WakeReason          string         `json:"wake_reason"`
	CaregiverIntervened sql.NullInt64  `json:"caregiver_intervened"`
	UpdatedAt           string         `json:"updated_at"`
	ID                  string         `json:"id"`
	FamilyID            string         `json:"family_id"`
}

func (q *Queries) EndSleep(ctx context.Context, arg EndSleepParams) error {
	_, err := q.db.ExecContext(ctx, endSleep,
		arg.EndedAt,
		arg.EndCondition,
		arg.WakeMood,
		arg.WakeReason,
		arg.CaregiverIntervened,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	return err
}

const existingGrowthMeasurementRevision = `-- name: ExistingGrowthMeasurementRevision :one
select revision from growth_measurements
where id=?1 and family_id=?2 and deleted_at is null
`

type ExistingGrowthMeasurementRevisionParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) ExistingGrowthMeasurementRevision(ctx context.Context, arg ExistingGrowthMeasurementRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existingGrowthMeasurementRevision, arg.ID, arg.FamilyID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const existingSleepRevision = `-- name: ExistingSleepRevision :one
select revision from sleep_sessions
where id=?1 and family_id=?2 and deleted_at is null
`

type ExistingSleepRevisionParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) ExistingSleepRevision(ctx context.Context, arg ExistingSleepRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existingSleepRevision, arg.ID, arg.FamilyID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const existingTemperatureReadingRevision = `-- name: ExistingTemperatureReadingRevision :one
select revision from temperature_readings where id=?1 and family_id=?2 and deleted_at is null
`

type ExistingTemperatureReadingRevisionParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) ExistingTemperatureReadingRevision(ctx context.Context, arg ExistingTemperatureReadingRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existingTemperatureReadingRevision, arg.ID, arg.FamilyID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const familyEventCount = `-- name: FamilyEventCount :one
select count(*) from sync_events where family_id=?1
`

func (q *Queries) FamilyEventCount(ctx context.Context, familyID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, familyEventCount, familyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const familySyncSnapshot = `-- name: FamilySyncSnapshot :one
select generation, cursor, entities_json, created_at
from family_sync_snapshots where family_id=?1
`

type FamilySyncSnapshotRow struct {
	Generation   string `json:"generation"`
	Cursor       int64  `json:"cursor"`
	EntitiesJson []byte `json:"entities_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) FamilySyncSnapshot(ctx context.Context, familyID string) (FamilySyncSnapshotRow, error) {
	row := q.db.QueryRowContext(ctx, familySyncSnapshot, familyID)
	var i FamilySyncSnapshotRow
	err := row.Scan(
		&i.Generation,
		&i.Cursor,
		&i.EntitiesJson,
		&i.CreatedAt,
	)
	return i, err
}

const growthMeasurementRecord = `-- name: GrowthMeasurementRecord :one
select id, family_id, child_id, measured_at, weight_grams, height_millimeters,
  note, revision, updated_at, deleted_at
from growth_measurements
where id=?1 and family_id=?2
`

type GrowthMeasurementRecordParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) GrowthMeasurementRecord(ctx context.Context, arg GrowthMeasurementRecordParams) (GrowthMeasurement, error) {
	row := q.db.QueryRowContext(ctx, growthMeasurementRecord, arg.ID, arg.FamilyID)
	var i GrowthMeasurement
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ChildID,
		&i.MeasuredAt,
		&i.WeightGrams,
		&i.HeightMillimeters,
		&i.Note,
		&i.Revision,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const growthReferencePoints = `-- name: GrowthReferencePoints :many
select reference, metric, age_months, sd, value
from growth_reference_points
order by reference, metric, age_months, sd
`

func (q *Queries) GrowthReferencePoints(ctx context.Context) ([]GrowthReferencePoint, error) {
	rows, err := q.db.QueryContext(ctx, growthReferencePoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GrowthReferencePoint{}
	for rows.Next() {
		var i GrowthReferencePoint
		if err := rows.Scan(
			&i.Reference,
			&i.Metric,
			&i.AgeMonths,
			&i.Sd,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestFamilyCursor = `-- name: LatestFamilyCursor :one
select cast(max(value) as integer) from (
  select coalesce(max(cursor), 0) as value from sync_events
  where sync_events.family_id=?1
  union all
  select coalesce(max(cursor), 0) as value from family_sync_snapshots
  where family_sync_snapshots.family_id=?1
) as latest_cursor
`

func (q *Queries) LatestFamilyCursor(ctx context.Context, familyID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestFamilyCursor, familyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
update deliveries set status='failed', last_error=?1, due_at=?2
where id=?3
`

type MarkDeliveryFailedParams struct {
	LastError sql.NullString `json:"last_error"`
	DueAt     string         `json:"due_at"`
	ID        string         `json:"id"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryFailed, arg.LastError, arg.DueAt, arg.ID)
	return err
}

const markDeliverySending = `-- name: MarkDeliverySending :execrows
update deliveries set status='sending', attempts=attempts+1, last_error=null
where id=?1 and status in ('pending', 'failed')
`

func (q *Queries) MarkDeliverySending(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markDeliverySending, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
update deliveries set status='sent', last_error=null where id=?1
`

func (q *Queries) MarkDeliverySent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markDeliverySent, id)
	return err
}

const predictionChild = `-- name: PredictionChild :one
select id, birth_date, prediction_mode, manual_interval_minutes, time_zone
from children
where family_id=?1 and deleted_at is null
order by updated_at limit 1
`

type PredictionChildRow struct {
	ID                    string        `json:"id"`
	BirthDate             string        `json:"birth_date"`
	PredictionMode        string        `json:"prediction_mode"`
	ManualIntervalMinutes sql.NullInt64 `json:"manual_interval_minutes"`
	TimeZone              string        `json:"time_zone"`
}

func (q *Queries) PredictionChild(ctx context.Context, familyID string) (PredictionChildRow, error) {
	row := q.db.QueryRowContext(ctx, predictionChild, familyID)
	var i PredictionChildRow
	err := row.Scan(
		&i.ID,
		&i.BirthDate,
		&i.PredictionMode,
		&i.ManualIntervalMinutes,
		&i.TimeZone,
	)
	return i, err
}

const presentSleep = `-- name: PresentSleep :exec
update sleep_sessions set
  started_at=?1,
  ended_at=?2,
  superseded_by_id=?3,
  revision=revision+1,
  updated_at=?4
where id=?5 and family_id=?6
`

type PresentSleepParams struct {
	StartedAt      string         `json:"started_at"`
	EndedAt        sql.NullString `json:"ended_at"`
	SupersededByID sql.NullString `json:"superseded_by_id"`
	UpdatedAt      string         `json:"updated_at"`
	ID             string         `json:"id"`
	FamilyID       string         `json:"family_id"`
}

func (q *Queries) PresentSleep(ctx context.Context, arg PresentSleepParams) error {
	_, err := q.db.ExecContext(ctx, presentSleep,
		arg.StartedAt,
		arg.EndedAt,
		arg.SupersededByID,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	return err
}

const queueDelivery = `-- name: QueueDelivery :exec
insert into deliveries(id, family_id, kind, payload_json, due_at, created_at)
values (
  ?1, ?2, ?3, ?4,
  ?5, ?6
)
`

type QueueDeliveryParams struct {
	ID          string `json:"id"`
	FamilyID    string `json:"family_id"`
	Kind        string `json:"kind"`
	PayloadJson []byte `json:"payload_json"`
	DueAt       string `json:"due_at"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) QueueDelivery(ctx context.Context, arg QueueDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, queueDelivery,
		arg.ID,
		arg.FamilyID,
		arg.Kind,
		arg.PayloadJson,
		arg.DueAt,
		arg.CreatedAt,
	)
	return err
}

const readEvents = `-- name: ReadEvents :many
select cursor, entity_type, entity_id, operation, revision, payload_json, created_at
from sync_events
where family_id=?1 and cursor>?2
order by cursor limit ?3
`

type ReadEventsParams struct {
	FamilyID    string `json:"family_id"`
	Cursor      int64  `json:"cursor"`
	ResultLimit int64  `json:"result_limit"`
}

type ReadEventsRow struct {
	Cursor      int64  `json:"cursor"`
	EntityType  string `json:"entity_type"`
	EntityID    string `json:"entity_id"`
	Operation   string `json:"operation"`
	Revision    int64  `json:"revision"`
	PayloadJson []byte `json:"payload_json"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) ReadEvents(ctx context.Context, arg ReadEventsParams) ([]ReadEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, readEvents, arg.FamilyID, arg.Cursor, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadEventsRow{}
	for rows.Next() {
		var i ReadEventsRow
		if err := rows.Scan(
			&i.Cursor,
			&i.EntityType,
			&i.EntityID,
			&i.Operation,
			&i.Revision,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCommand = `-- name: RecordCommand :exec
insert into commands(id, family_id, user_id, kind, result_json, created_at)
values (?1, ?2, ?3, ?4, ?5, ?6)
on conflict(family_id, id) do nothing
`

type RecordCommandParams struct {
	ID         string `json:"id"`
	FamilyID   string `json:"family_id"`
	UserID     string `json:"user_id"`
	Kind       string `json:"kind"`
	ResultJson []byte `json:"result_json"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) RecordCommand(ctx context.Context, arg RecordCommandParams) error {
	_, err := q.db.ExecContext(ctx, recordCommand,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
		arg.Kind,
		arg.ResultJson,
		arg.CreatedAt,
	)
	return err
}

const recordedActiveSleep = `-- name: RecordedActiveSleep :one
select id, recorded_started_at, revision from sleep_sessions
where family_id=?1
  and id=?2
  and recorded_ended_at is null
  and deleted_at is null
`

type RecordedActiveSleepParams struct {
	FamilyID string `json:"family_id"`
	ID       string `json:"id"`
}

type RecordedActiveSleepRow struct {
	ID                string `json:"id"`
	RecordedStartedAt string `json:"recorded_started_at"`
	Revision          int64  `json:"revision"`
}

// An unfinished recorded sleep can be ended even while the presentation shows
// it ended by a later sleep or folded into another session.
func (q *Queries) RecordedActiveSleep(ctx context.Context, arg RecordedActiveSleepParams) (RecordedActiveSleepRow, error) {
	row := q.db.QueryRowContext(ctx, recordedActiveSleep, arg.FamilyID, arg.ID)
	var i RecordedActiveSleepRow
	err := row.Scan(&i.ID, &i.RecordedStartedAt, &i.Revision)
	return i, err
}

const resetSendingDeliveries = `-- name: ResetSendingDeliveries :exec
update deliveries set status='failed', last_error='backend restarted during delivery'
where status='sending'
`

func (q *Queries) ResetSendingDeliveries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSendingDeliveries)
	return err
}

const sleepIntervals = `-- name: SleepIntervals :many
select id, recorded_started_at, recorded_ended_at, started_at, ended_at, superseded_by_id
from sleep_sessions
where family_id=?1
  and child_id=?2
  and deleted_at is null
order by recorded_started_at, id
`

type SleepIntervalsParams struct {
	FamilyID string `json:"family_id"`
	ChildID  string `json:"child_id"`
}

type SleepIntervalsRow struct {
	ID                string         `json:"id"`
	RecordedStartedAt string         `json:"recorded_started_at"`
	RecordedEndedAt   sql.NullString `json:"recorded_ended_at"`
	StartedAt         string         `json:"started_at"`
	EndedAt           sql.NullString `json:"ended_at"`
	SupersededByID    sql.NullString `json:"superseded_by_id"`
}

func (q *Queries) SleepIntervals(ctx context.Context, arg SleepIntervalsParams) ([]SleepIntervalsRow, error) {
	rows, err := q.db.QueryContext(ctx, sleepIntervals, arg.FamilyID, arg.ChildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SleepIntervalsRow{}
	for rows.Next() {
		var i SleepIntervalsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordedStartedAt,
			&i.RecordedEndedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.SupersededByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sleepRecord = `-- name: SleepRecord :one
select id, family_id, child_id, started_at, ended_at, revision,
  author_id, source, start_condition, sleep_location, end_condition,
  wake_mood, wake_reason, caregiver_intervened, superseded_by_id, updated_at, deleted_at
from sleep_sessions
where id=?1 and family_id=?2
`

type SleepRecordParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

type SleepRecordRow struct {
	ID                  string         `json:"id"`
	FamilyID            string         `json:"family_id"`
	ChildID             string         `json:"child_id"`
	StartedAt           string         `json:"started_at"`
	EndedAt             sql.NullString `json:"ended_at"`
	Revision            int64          `json:"revision"`
	AuthorID            string         `json:"author_id"`
	Source              string         `json:"source"`
	StartCondition      string         `json:"start_condition"`
	SleepLocation       string         `json:"sleep_location"`
	EndCondition        string         `json:"end_condition"`
	WakeMood            string         `json:"wake_mood"`
	WakeReason          string         `json:"wake_reason"`
	CaregiverIntervened sql.NullInt64  `json:"caregiver_intervened"`
	SupersededByID      sql.NullString `json:"superseded_by_id"`
	UpdatedAt           string         `json:"updated_at"`
	DeletedAt           sql.NullString `json:"deleted_at"`
}

func (q *Queries) SleepRecord(ctx context.Context, arg SleepRecordParams) (SleepRecordRow, error) {
	row := q.db.QueryRowContext(ctx, sleepRecord, arg.ID, arg.FamilyID)
	var i SleepRecordRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ChildID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Revision,
		&i.AuthorID,
		&i.Source,
		&i.StartCondition,
		&i.SleepLocation,
		&i.EndCondition,
		&i.WakeMood,
		&i.WakeReason,
		&i.CaregiverIntervened,
		&i.SupersededByID,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const snapshotChildIDs = `-- name: SnapshotChildIDs :many
select id from children
where family_id=?1
order by id
`

// Snapshots include tombstones: a client replaying its journal after a reset
// must see that a replayed create was later deleted, or it resurrects it.
func (q *Queries) SnapshotChildIDs(ctx context.Context, familyID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, snapshotChildIDs, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotGrowthIDs = `-- name: SnapshotGrowthIDs :many
select id from growth_measurements where family_id=?1 order by id
`

func (q *Queries) SnapshotGrowthIDs(ctx context.Context, familyID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, snapshotGrowthIDs, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotSleepIDs = `-- name: SnapshotSleepIDs :many
select id from sleep_sessions
where family_id=?1
order by id
`

func (q *Queries) SnapshotSleepIDs(ctx context.Context, familyID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, snapshotSleepIDs, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotTemperatureIDs = `-- name: SnapshotTemperatureIDs :many
select id from temperature_readings where family_id=?1 order by id
`

func (q *Queries) SnapshotTemperatureIDs(ctx context.Context, familyID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, snapshotTemperatureIDs, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweetSpotHistory = `-- name: SweetSpotHistory :many
select started_at, ended_at, start_condition, sleep_location, end_condition,
  wake_mood, wake_reason, caregiver_intervened
from sleep_sessions
where child_id=?1
  and ended_at is not null
  and deleted_at is null
  and superseded_by_id is null
order by started_at
`

type SweetSpotHistoryRow struct {
	StartedAt           string         `json:"started_at"`
	EndedAt             sql.NullString `json:"ended_at"`
	StartCondition      string         `json:"start_condition"`
	SleepLocation       string         `json:"sleep_location"`
	EndCondition        string         `json:"end_condition"`
	WakeMood            string         `json:"wake_mood"`
	WakeReason          string         `json:"wake_reason"`
	CaregiverIntervened sql.NullInt64  `json:"caregiver_intervened"`
}

func (q *Queries) SweetSpotHistory(ctx context.Context, childID string) ([]SweetSpotHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, sweetSpotHistory, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SweetSpotHistoryRow{}
	for rows.Next() {
		var i SweetSpotHistoryRow
		if err := rows.Scan(
			&i.StartedAt,
			&i.EndedAt,
			&i.StartCondition,
			&i.SleepLocation,
			&i.EndCondition,
			&i.WakeMood,
			&i.WakeReason,
			&i.CaregiverIntervened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const temperatureReadingRecord = `-- name: TemperatureReadingRecord :one
select id, family_id, child_id, measured_at, centi_celsius, note, revision, updated_at, deleted_at
from temperature_readings where id=?1 and family_id=?2
`

type TemperatureReadingRecordParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) TemperatureReadingRecord(ctx context.Context, arg TemperatureReadingRecordParams) (TemperatureReading, error) {
	row := q.db.QueryRowContext(ctx, temperatureReadingRecord, arg.ID, arg.FamilyID)
	var i TemperatureReading
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ChildID,
		&i.MeasuredAt,
		&i.CentiCelsius,
		&i.Note,
		&i.Revision,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateChild = `-- name: UpdateChild :exec
update children set
  nickname=coalesce(nullif(?1, ''), nickname),
  birth_date=coalesce(nullif(?2, ''), birth_date),
  prediction_mode=?3,
  manual_interval_minutes=?4,
  quiet_hours_start_minutes=?5,
  quiet_hours_end_minutes=?6,
  time_zone=coalesce(nullif(?7, ''), time_zone),
  growth_reference=coalesce(nullif(?8, ''), growth_reference),
  revision=revision+1,
  updated_at=?9
where id=?10 and family_id=?11
`

type UpdateChildParams struct {
	Nickname               interface{}   `json:"nickname"`
	BirthDate              interface{}   `json:"birth_date"`
	PredictionMode         string        `json:"prediction_mode"`
	ManualIntervalMinutes  sql.NullInt64 `json:"manual_interval_minutes"`
	QuietHoursStartMinutes int64         `json:"quiet_hours_start_minutes"`
	QuietHoursEndMinutes   int64         `json:"quiet_hours_end_minutes"`
	TimeZone               interface{}   `json:"time_zone"`
	GrowthReference        interface{}   `json:"growth_reference"`
	UpdatedAt              string        `json:"updated_at"`
	ID                     string        `json:"id"`
	FamilyID               string        `json:"family_id"`
}

func (q *Queries) UpdateChild(ctx context.Context, arg UpdateChildParams) error {
	_, err := q.db.ExecContext(ctx, updateChild,
		arg.Nickname,
		arg.BirthDate,
		arg.PredictionMode,
		arg.ManualIntervalMinutes,
		arg.QuietHoursStartMinutes,
		arg.QuietHoursEndMinutes,
		arg.TimeZone,
		arg.GrowthReference,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	return err
}

const updateGrowthMeasurement = `-- name: UpdateGrowthMeasurement :exec
update growth_measurements set
  measured_at=?1,
  weight_grams=?2,
  height_millimeters=?3,
  note=?4,
  revision=revision+1,
  updated_at=?5
where id=?6 and family_id=?7
`

type UpdateGrowthMeasurementParams struct {
	MeasuredAt        string        `json:"measured_at"`
	WeightGrams       sql.NullInt64 `json:"weight_grams"`
	HeightMillimeters sql.NullInt64 `json:"height_millimeters"`
	Note              string        `json:"note"`
	UpdatedAt         string        `json:"updated_at"`
	ID                string        `json:"id"`
	FamilyID          string        `json:"family_id"`
}

func (q *Queries) UpdateGrowthMeasurement(ctx context.Context, arg UpdateGrowthMeasurementParams) error {
	_, err := q.db.ExecContext(ctx, updateGrowthMeasurement,
		arg.MeasuredAt,
		arg.WeightGrams,
		arg.HeightMillimeters,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	return err
}

const updateSleep = `-- name: UpdateSleep :exec
update sleep_sessions set
  recorded_started_at=?1,
  recorded_ended_at=?2,
  started_at=?1,
  ended_at=?2,
  start_condition=?3,
  sleep_location=?4,
  end_condition=?5,
  wake_mood=?6,
  wake_reason=?7,
  caregiver_intervened=?8,
  revision=revision+1,
  updated_at=?9
where id=?10 and family_id=?11
`

type UpdateSleepParams struct {
	StartedAt           string         `json:"started_at"`
	EndedAt             sql.NullString `json:"ended_at"`
	StartCondition      string         `json:"start_condition"`
	SleepLocation       string         `json:"sleep_location"`
	EndCondition        string         `json:"end_condition"`
	WakeMood            string         `json:"wake_mood"`
	WakeReason          string         `json:"wake_reason"`
	CaregiverIntervened sql.NullInt64  `json:"caregiver_intervened"`
	UpdatedAt           string         `json:"updated_at"`
	ID                  string         `json:"id"`
	FamilyID            string         `json:"family_id"`
}

func (q *Queries) UpdateSleep(ctx context.Context, arg UpdateSleepParams) error {
	_, err := q.db.ExecContext(ctx, updateSleep,
		arg.StartedAt,
		arg.EndedAt,
		arg.StartCondition,
		arg.SleepLocation,
		arg.EndCondition,
		arg.WakeMood,
		arg.WakeReason,
		arg.CaregiverIntervened,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	return err
}

const updateTemperatureReading = `-- name: UpdateTemperatureReading :exec
update temperature_readings set measured_at=?1, centi_celsius=?2,
  note=?3, revision=revision+1, updated_at=?4
where id=?5 and family_id=?6
`

type UpdateTemperatureReadingParams struct {
	MeasuredAt   string `json:"measured_at"`
	CentiCelsius int64  `json:"centi_celsius"`
	Note         string `json:"note"`
	UpdatedAt    string `json:"updated_at"`
	ID           string `json:"id"`
	FamilyID     string `json:"family_id"`
}

func (q *Queries) UpdateTemperatureReading(ctx context.Context, arg UpdateTemperatureReadingParams) error {
	_, err := q.db.ExecContext(ctx, updateTemperatureReading,
		arg.MeasuredAt,
		arg.CentiCelsius,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
		arg.FamilyID,
	)
	return err
}

const upsertFamilySyncSnapshot = `-- name: UpsertFamilySyncSnapshot :exec
insert into family_sync_snapshots(family_id, generation, cursor, entities_json, created_at)
values (?1, ?2, ?3, ?4, ?5)
on conflict(family_id) do update set
  generation=excluded.generation,
  cursor=excluded.cursor,
  entities_json=excluded.entities_json,
  created_at=excluded.created_at
`

type UpsertFamilySyncSnapshotParams struct {
	FamilyID     string `json:"family_id"`
	Generation   string `json:"generation"`
	Cursor       int64  `json:"cursor"`
	EntitiesJson []byte `json:"entities_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) UpsertFamilySyncSnapshot(ctx context.Context, arg UpsertFamilySyncSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertFamilySyncSnapshot,
		arg.FamilyID,
		arg.Generation,
		arg.Cursor,
		arg.EntitiesJson,
		arg.CreatedAt,
	)
	return err
}
